id: logs
displayName: Display name
description: |
  ## Description
  ## Supports markdown
icon: logo.svg
install:
  primary:
    link:
      url: https://www.newrelic.com
keywords:
  - List
  - of
  - searchable
  - keywords
categoryTerms:
  - newrelic partner
  - logs
